# Generated by Django 2.1.3 on 2018-11-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Category', models.CharField(default='B1', max_length=2)),
                ('HR_name', models.CharField(default='-', max_length=30)),
                ('HR_contact', models.EmailField(max_length=100, unique=True)),
                ('Sector', models.CharField(default='IT', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Roll_no', models.CharField(max_length=8)),
                ('CPI', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Dept', models.CharField(default='-', max_length=30)),
                ('Course', models.CharField(default='-', max_length=30)),
                ('Resume', models.URLField()),
            ],
        ),
    ]
