# Generated by Django 2.1.3 on 2018-12-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpcm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('pos', 'stud')},
        ),
    ]
