# Generated by Django 2.1.3 on 2018-11-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpcm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='HR_contact',
            new_name='hr_contact',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='HR_name',
            new_name='hr_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='Sector',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='CPI',
            new_name='cpi',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Dept',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Resume',
            new_name='resume',
        ),
        migrations.AddField(
            model_name='company',
            name='date_of_visit',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
