# Generated by Django 2.1.3 on 2018-12-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpcm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='company',
            field=models.CharField(default='self', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='branch_appl',
            field=models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('ME', 'ME'), ('CB', 'CB'), ('CE', 'CE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='course_appl',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('M.Sc', 'M.Sc')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('M.Sc', 'M.Sc')], default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('CS', 'CS'), ('EE', 'EE'), ('ME', 'ME'), ('CB', 'CB'), ('CE', 'CE')], default='-', max_length=30),
        ),
    ]
