# Generated by Django 2.1.3 on 2018-12-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpcm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='cmp_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpcm_app.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='jobposition',
            unique_together={('cmp_name', 'pos_name')},
        ),
    ]
