# Generated by Django 2.1.3 on 2018-12-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpcm_app', '0002_auto_20181203_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='company',
        ),
    ]
