# Generated by Django 2.1.3 on 2018-11-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpcm_app', '0002_auto_20181129_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_of_visit',
            field=models.DateField(),
        ),
    ]
