# Generated by Django 2.1.3 on 2018-12-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpcm_app', '0003_auto_20181202_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='pos_name',
            field=models.CharField(help_text='This is the grey text', max_length=30),
        ),
    ]
