# Generated by Django 2.1.3 on 2018-12-03 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpcm_app', '0003_remove_jobposition_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='cmp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpcm_app.Company'),
        ),
    ]
