# Generated by Django 2.1.3 on 2018-11-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpcm_app', '0003_auto_20181129_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_of_visit',
            field=models.DateField(null=True),
        ),
    ]
