# Generated by Django 2.1.3 on 2018-12-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpcm_app', '0004_auto_20181203_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='cmp_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tpcm_app.Company'),
        ),
    ]
