# Generated by Django 2.1.3 on 2018-11-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Roll_no', models.CharField(max_length=8)),
                ('Department', models.CharField(max_length=30)),
                ('CPI', models.IntegerField()),
                ('Resume', models.URLField()),
            ],
        ),
    ]
